// Generated by Ember
// import ApplicationAdapter from './application';

// export default ApplicationAdapter.extend({
// });

// From blogpost
import DS from 'ember-data';

export default DS.ActiveModelAdapter.extend({
  // namespace: 'api/v1',
  host: 'http://localhost:3000'
});
